import '../lib/src/store.dart';

const testResidentialName = 'Test Residential';
const testBusinessName = 'Test Business Centre';

/// In-memory catalogue for server tests — never shipped to production.
Store createTestStore() {
  final store = Store();
  seedTestCatalogue(store);
  return store;
}

void seedTestCatalogue(Store store) {
  if (store.projects.isNotEmpty) return;

  const developer = {
    'id': 'dev-test',
    'name': 'Test Developer',
    'logoUrl': null,
    'rating': 4.5,
    'projectsCount': 2,
    'phone': '+998901234567',
    'agentName': 'Test Agent',
    'agentPhone': '+998901234567',
    'agentAvatarUrl': null,
    'verificationStatus': 'approved',
    'rejectionReason': null,
    'ownerUserId': 'usr-test-dev',
    'legalName': 'Test Developer LLC',
    'inn': null,
    'website': null,
    'createdAt': '2026-01-01T00:00:00.000Z',
  };

  store.developersRegistry.add(Map<String, dynamic>.from(developer));

  store.projects.addAll([
    {
      'id': 'prj-test-residential',
      'name': testResidentialName,
      'type': 'residential_complex',
      'status': 'ready',
      'district': 'Yunusabad',
      'address': 'Test address 1',
      'lat': 41.33,
      'lng': 69.28,
      'developer': Map<String, dynamic>.from(developer)
        ..removeWhere(
          (k, _) => !{
            'id',
            'name',
            'logoUrl',
            'rating',
            'projectsCount',
            'phone',
            'agentName',
            'agentPhone',
            'agentAvatarUrl',
          }.contains(k),
        ),
      'description': 'Test residential project',
      'amenities': ['Gym', 'Parking'],
      'tags': ['Test'],
      'priceMin': 50000.0,
      'priceMax': 120000.0,
      'rentMin': 400.0,
      'rentMax': 900.0,
      'constructionProgress': 80,
      'plannedProgress': 85,
      'completionDate': '2027-06-01T00:00:00.000Z',
      'rating': 4.5,
      'availableUnits': 2,
      'totalUnits': 3,
      'isFeatured': true,
      'isPublished': true,
      'moderationStatus': 'approved',
      'moderationNote': null,
      'gallery': [],
      'offers': [
        {
          'id': 'off-installment',
          'projectId': 'prj-test-residential',
          'type': 'installment',
          'title': 'Test installment',
          'description': null,
          'startsAt': null,
          'endsAt': '2027-01-01T00:00:00.000Z',
          'downPaymentPercent': 0.3,
          'termMonths': 24,
          'interestRate': 0.0,
        },
        {
          'id': 'off-discount',
          'projectId': 'prj-test-residential',
          'type': 'discount',
          'title': 'Test discount',
          'description': null,
          'startsAt': null,
          'endsAt': null,
          'downPaymentPercent': null,
          'termMonths': null,
          'interestRate': null,
        },
      ],
      'buildings': [
        {
          'id': 'bld-test-res',
          'projectId': 'prj-test-residential',
          'name': 'Block A',
          'floors': 5,
          'constructionProgress': 80,
          'completionDate': '2027-06-01T00:00:00.000Z',
          'units': [
            {
              'id': 'unit-test-sale',
              'buildingId': 'bld-test-res',
              'number': '101',
              'kind': 'apartment',
              'dealType': 'sale',
              'status': 'available',
              'floor': 1,
              'isOffplan': false,
              'areaTotal': 62.0,
              'areaLiving': 54.0,
              'rooms': 2,
              'layout': null,
              'price': 75000.0,
              'priceM2': 1209.0,
              'rentMonthly': null,
              'rentM2': null,
              'minLeaseMonths': null,
              'finishing': 'Turnkey',
              'view': 'City',
              'planColumn': 0,
              'planRow': 0,
              'version': 1,
              'media': [],
            },
            {
              'id': 'unit-test-rent',
              'buildingId': 'bld-test-res',
              'number': '102',
              'kind': 'apartment',
              'dealType': 'rent',
              'status': 'available',
              'floor': 1,
              'isOffplan': false,
              'areaTotal': 48.0,
              'areaLiving': 41.0,
              'rooms': 1,
              'layout': null,
              'price': null,
              'priceM2': null,
              'rentMonthly': 500.0,
              'rentM2': 10.4,
              'minLeaseMonths': 12,
              'finishing': 'Turnkey',
              'view': 'Park',
              'planColumn': 1,
              'planRow': 0,
              'version': 1,
              'media': [],
            },
          ],
        },
      ],
    },
    {
      'id': 'prj-test-business',
      'name': testBusinessName,
      'type': 'business_centre',
      'status': 'ready',
      'district': 'Mirabad',
      'address': 'Test address 2',
      'lat': 41.31,
      'lng': 69.27,
      'developer': Map<String, dynamic>.from(developer)
        ..removeWhere(
          (k, _) => !{
            'id',
            'name',
            'logoUrl',
            'rating',
            'projectsCount',
            'phone',
            'agentName',
            'agentPhone',
            'agentAvatarUrl',
          }.contains(k),
        ),
      'description': 'Test business centre',
      'amenities': ['Reception'],
      'tags': ['Test'],
      'priceMin': null,
      'priceMax': null,
      'rentMin': 800.0,
      'rentMax': 2500.0,
      'constructionProgress': null,
      'plannedProgress': null,
      'completionDate': null,
      'rating': 4.2,
      'availableUnits': 1,
      'totalUnits': 1,
      'isFeatured': false,
      'isPublished': true,
      'moderationStatus': 'approved',
      'moderationNote': null,
      'gallery': [],
      'offers': [],
      'buildings': [
        {
          'id': 'bld-test-bc',
          'projectId': 'prj-test-business',
          'name': 'Tower',
          'floors': 10,
          'constructionProgress': null,
          'completionDate': null,
          'units': [
            {
              'id': 'unit-test-office',
              'buildingId': 'bld-test-bc',
              'number': '501',
              'kind': 'office',
              'dealType': 'rent',
              'status': 'available',
              'floor': 5,
              'isOffplan': false,
              'areaTotal': 120.0,
              'areaLiving': null,
              'rooms': null,
              'layout': 'open-plan',
              'price': null,
              'priceM2': null,
              'rentMonthly': 1200.0,
              'rentM2': 10.0,
              'minLeaseMonths': 12,
              'finishing': 'Shell',
              'view': 'City',
              'planColumn': 0,
              'planRow': 4,
              'version': 1,
              'media': [],
            },
          ],
        },
      ],
    },
  ]);

  store.leads.add({
    'id': 'lead-test-1',
    'number': 'LD-100001',
    'projectId': 'prj-test-residential',
    'projectName': testResidentialName,
    'unitId': 'unit-test-sale',
    'unitLabel': 'Apartment 101',
    'intent': 'viewing',
    'status': 'new',
    'contactPhone': '+998901234567',
    'message': 'Test lead',
    'preferredAt': null,
    'createdAt': DateTime.now().toIso8601String(),
  });
}
